# Generated by Django 5.1.4 on 2025-01-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('light_level', models.CharField(max_length=50)),
                ('humidity', models.CharField(max_length=50)),
                ('plant_type', models.CharField(max_length=50)),
                ('watering_frequency', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
            ],
        ),
    ]
