# Generated by Django 5.1.4 on 2025-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_plants'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('light_level', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('plant_type', models.CharField(max_length=100)),
                ('watering_frequency', models.CharField(max_length=20)),
                ('soil_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Plants',
        ),
    ]
